RESHAPING IN PYTHON

Reshaping NumPy arrays

#reshape() function

In [2]:
import numpy as np
array1=np.arange(0,12)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
array2=array1.reshape(3,4)
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
array3=array1.reshape(2,2,3)
array3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [5]:
array4=array1.reshape(3,2,2)
array4

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [6]:
array5=np.arange(0,9).reshape(3,3)
array5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

using shape()function

In [7]:
array1=np.arange(0,12)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
array1.shape

(12,)

In [9]:
array1.shape=(3,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

using resize() function

In [10]:
array1=np.arange(0,12)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
array1.resize(3,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

numpy.reshape() in python

In [12]:
import numpy as np
array=np.arange(8)
print("original array:\n",array)
#shape array with 2 rows and 4 columns
array=np.arange(8).reshape(2,4)
print("\narray reshaped with 2 rows and 4 columns:\n",array)
#shape array with 4 rows and 2 columns
array=np.arange(8).reshape(4,2)
print("\narray reshaped with 4 rows and 2 columns:\n",array)
#constructs 3-D array
array=np.arange(8).reshape(2,2,2)
print("\n original array reshaped to 3D:\n",array)

original array:
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns:
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 4 rows and 2 columns:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

 original array reshaped to 3D:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
